// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Presentation.DataAccess.Models
{
    public partial class WeatherCondition
    {
        public int Id { get; set; }
        public int ElementId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
    }
}