// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Presentation.DataAccess.Models
{
    public partial class WeatherElement
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public string ElementName { get; set; }
    }
}